const fs = require('fs');
const path = require('path');

const lines = [];

lines.push('-- ============================================================================');
lines.push('-- SCHEMA SUPABASE - GRADE HORARIA COM ADMIN/ALUNO + REALTIME');
lines.push('-- ============================================================================');
lines.push('');
lines.push('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";');
lines.push('CREATE EXTENSION IF NOT EXISTS "pgcrypto";');
lines.push('');
lines.push('CREATE TYPE user_role AS ENUM (\'admin\', \'student\');');
lines.push('CREATE TYPE day_of_week AS ENUM (\'monday\', \'tuesday\', \'wednesday\', \'thursday\', \'friday\', \'saturday\');');
lines.push('');
lines.push('CREATE TABLE profiles (');
lines.push('    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,');
lines.push('    email TEXT NOT NULL,');
lines.push('    full_name TEXT,');
lines.push('    role user_role NOT NULL DEFAULT \'student\',');
lines.push('    avatar_url TEXT,');
lines.push('    created_at TIMESTAMPTZ DEFAULT NOW(),');
lines.push('    updated_at TIMESTAMPTZ DEFAULT NOW()');
lines.push(');');
lines.push('');
lines.push('CREATE OR REPLACE FUNCTION update_updated_at_column()');
lines.push('RETURNS TRIGGER AS $$');
lines.push('BEGIN');
lines.push('    NEW.updated_at = NOW();');
lines.push('    RETURN NEW;');
lines.push('END;');
lines.push('$$ LANGUAGE plpgsql;');
lines.push('');
lines.push('CREATE TRIGGER update_profiles_updated_at');
lines.push('    BEFORE UPDATE ON profiles');
lines.push('    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();');
lines.push('');
lines.push('CREATE TABLE subjects (');
lines.push('    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),');
lines.push('    code TEXT NOT NULL UNIQUE,');
lines.push('    name TEXT NOT NULL,');
lines.push('    credits INTEGER NOT NULL DEFAULT 4,');
lines.push('    workload INTEGER NOT NULL DEFAULT 60,');
lines.push('    professor TEXT,');
lines.push('    semester INTEGER,');
lines.push('    prerequisites UUID[] DEFAULT \'{}\',');
lines.push('    corequisites UUID[] DEFAULT \'{}\',');
lines.push('    schedule JSONB DEFAULT \'{}\',');
lines.push('    description TEXT,');
lines.push('');
lines.push('CREATE TRIGGER update_subjects_updated_at');
lines.push('    BEFORE UPDATE ON subjects');
lines.push('    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();');
lines.push('');
lines.push('CREATE TABLE grades (');
lines.push('    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),');
lines.push('    student_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,');
lines.push('    name TEXT NOT NULL DEFAULT \'Minha Grade\',');
lines.push('    semester INTEGER NOT NULL,');
lines.push('    year INTEGER NOT NULL,');
lines.push('    is_active BOOLEAN DEFAULT TRUE,');
lines.push('    is_public BOOLEAN DEFAULT FALSE,');
lines.push('    created_at TIMESTAMPTZ DEFAULT NOW(),');
lines.push('    updated_at TIMESTAMPTZ DEFAULT NOW(),');
lines.push('    UNIQUE(student_id, semester, year, is_active)');
lines.push(');');
lines.push('');
lines.push('CREATE TRIGGER update_grades_updated_at');
lines.push('    BEFORE UPDATE ON grades');
lines.push('    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();');
lines.push('');
lines.push('CREATE TABLE grade_subjects (');
lines.push('    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),');
lines.push('    grade_id UUID NOT NULL REFERENCES grades(id) ON DELETE CASCADE,');
lines.push('    subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,');
lines.push('    day day_of_week NOT NULL,');
lines.push('    time_start TIME NOT NULL,');
lines.push('    time_end TIME NOT NULL,');
lines.push('    classroom TEXT,');
lines.push('    color TEXT DEFAULT \'#3B82F6\',');
lines.push('    created_at TIMESTAMPTZ DEFAULT NOW(),');
lines.push('    UNIQUE(grade_id, subject_id)');
lines.push(');');
lines.push('');
lines.push('CREATE TABLE student_subjects (');
lines.push('    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),');
lines.push('    student_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,');
lines.push('    subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,');
lines.push('    grade_id UUID REFERENCES grades(id) ON DELETE SET NULL,');
lines.push('    status TEXT DEFAULT \'enrolled\' CHECK (status IN (\'enrolled\', \'completed\', \'dropped\', \'pending\')),');
lines.push('    final_grade NUMERIC(4,2),');
lines.push('    created_at TIMESTAMPTZ DEFAULT NOW(),');
lines.push('    UNIQUE(student_id, subject_id, grade_id)');
lines.push(');');
lines.push('');
lines.push('ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;');
lines.push('ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;');
lines.push('ALTER TABLE grades ENABLE ROW LEVEL SECURITY;');
lines.push('ALTER TABLE grade_subjects ENABLE ROW LEVEL SECURITY;');
lines.push('');
lines.push('CREATE POLICY "Profiles visiveis" ON profiles FOR SELECT USING (TRUE);');
lines.push('CREATE POLICY "Usuario atualiza perfil" ON profiles FOR UPDATE USING (auth.uid() = id);');
lines.push('CREATE POLICY "Admin gerencia perfis" ON profiles FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = \'admin\'));');
lines.push('');
lines.push('CREATE POLICY "Materias publicas" ON subjects FOR SELECT USING (is_active = TRUE);');
lines.push('CREATE POLICY "Admin CRUD materias" ON subjects FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = \'admin\'));');
lines.push('');
lines.push('CREATE POLICY "Aluno ve grades" ON grades FOR SELECT USING (student_id = auth.uid() OR is_public = TRUE);');
lines.push('CREATE POLICY "Aluno gerencia grades" ON grades FOR ALL USING (student_id = auth.uid());');
lines.push('CREATE POLICY "Admin ve grades" ON grades FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = \'admin\'));');
lines.push('');
lines.push('CREATE POLICY "Grade subjects seguem grade" ON grade_subjects FOR SELECT USING (EXISTS (SELECT 1 FROM grades WHERE grades.id = grade_subjects.grade_id AND (grades.student_id = auth.uid() OR grades.is_public = TRUE)));');
lines.push('CREATE POLICY "Aluno gerencia grade_subjects" ON grade_subjects FOR ALL USING (EXISTS (SELECT 1 FROM grades WHERE grades.id = grade_subjects.grade_id AND grades.student_id = auth.uid()));');
lines.push('CREATE POLICY "Admin gerencia grade_subjects" ON grade_subjects FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = \'admin\'));');
lines.push('');
lines.push('CREATE POLICY "Ver matriculas e colegas" ON student_subjects FOR SELECT USING (student_id = auth.uid() OR subject_id IN (SELECT subject_id FROM student_subjects WHERE student_id = auth.uid()));');
lines.push('CREATE POLICY "Aluno gerencia matriculas" ON student_subjects FOR ALL USING (student_id = auth.uid());');
lines.push('CREATE POLICY "Admin gerencia matriculas" ON student_subjects FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = \'admin\'));');
lines.push('');
lines.push('CREATE OR REPLACE FUNCTION public.handle_new_user()');
lines.push('RETURNS TRIGGER AS $$');
lines.push('BEGIN');
lines.push('    INSERT INTO public.profiles (id, email, full_name, role)');
lines.push('    VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>\'full_name\', CASE WHEN NEW.email = \'seu-email@gmail.com\' THEN \'admin\' ELSE \'student\' END)');
lines.push('    ON CONFLICT (id) DO NOTHING;');
lines.push('    RETURN NEW;');
lines.push('EXCEPTION WHEN OTHERS THEN RETURN NEW;');
lines.push('END;');
lines.push('$$ LANGUAGE plpgsql SECURITY DEFINER;');
lines.push('');
lines.push('DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;');
lines.push('CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();');
lines.push('');
lines.push('ALTER PUBLICATION supabase_realtime ADD TABLE profiles;');
lines.push('ALTER PUBLICATION supabase_realtime ADD TABLE subjects;');
lines.push('ALTER PUBLICATION supabase_realtime ADD TABLE grades;');
lines.push('ALTER PUBLICATION supabase_realtime ADD TABLE grade_subjects;');
lines.push('ALTER PUBLICATION supabase_realtime ADD TABLE student_subjects;');
lines.push('');
lines.push('INSERT INTO subjects (code, name, credits, workload, professor, semester, schedule, description) VALUES');
lines.push('(\'CCO101\', \'Algoritmos e Programacao\', 4, 60, \'Prof. Silva\', 1, \'{"monday": [{"start": "07:30", "end": "09:10"}], "wednesday": [{"start": "07:30", "end": "09:10"}]}\', \'Logica de programacao\'),');
lines.push('(\'CCO102\', \'Calculo I\', 4, 60, \'Prof. Santos\', 1, \'{"tuesday": [{"start": "09:20", "end": "11:00"}], "thursday": [{"start": "09:20", "end": "11:00"}]}\', \'Limites, derivadas\'),');
lines.push('(\'CCO103\', \'Algebra Linear\', 4, 60, \'Prof. Oliveira\', 1, \'{"monday": [{"start": "09:20", "end": "11:00"}], "friday": [{"start": "07:30", "end": "09:10"}]}\', \'Matrizes, vetores\'),');
lines.push('(\'CCO201\', \'Estruturas de Dados\', 4, 60, \'Prof. Costa\', 2, \'{"tuesday": [{"start": "07:30", "end": "09:10"}], "thursday": [{"start": "07:30", "end": "09:10"}]}\', \'Listas, pilhas, filas, arvores\')');
lines.push('ON CONFLICT (code) DO NOTHING;');

const schema = lines.join('\n');
fs.writeFileSync(path.join(__dirname, 'schema.sql'), schema, 'utf8');
console.log('schema.sql criado com sucesso!');
lines.push('ALTER TABLE student_subjects ENABLE ROW LEVEL SECURITY;');
lines.push('    is_active BOOLEAN DEFAULT TRUE,');
lines.push('    created_by UUID REFERENCES profiles(id),');
lines.push('    created_at TIMESTAMPTZ DEFAULT NOW(),');
lines.push('    updated_at TIMESTAMPTZ DEFAULT NOW()');
lines.push(');');